# -*- coding: utf-8 -*-
"""Factorial05_25BCON0879.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fdtI9Gimj2b0UYv8XHys1SsY0-b1FgK5
"""

n = 5
fact = 1

for i in range(1, n + 1):
    fact = fact * i

print(f"Factorial of {n}: {fact}")