# -*- coding: utf-8 -*-
"""Factorial05_25BCON0879.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fdtI9Gimj2b0UYv8XHys1SsY0-b1FgK5
"""

n = 10
a = 0
b = 1

for i in range(n):
    print(a, end=" ")

    next = a + b
    a = b
    b = next

class Student:
    def __init__(self,name,roll_no,marks):
        self.name=name
        self.roll_no=roll_no
        self.marks=marks

s1=Student("Rahul",101,87.5)
print("Student Details:")
print("Name:",s1.name)
print("Roll No:",s1.roll_no)
print("Marks: {:.2f}".format(s1.marks))