a=input("Name    : ")
b=int(input("Class   : "))
c=input("Section : ")
d=int(input("English Marks     : "))
e=int(input("Economics Marks   : "))
f=int(input("Accounts Marks    : "))
g=int(input("BST Marks         : "))
h=int(input("Informatics Marks : "))
r=input("Remarks : ")
i=(d+e+f+g+h)
j=(i/5)
print()
print("-"*100)
print("                                        REPORT CARD")
("_"*100)
print("-"*100)
print("                                    STUDENT INFORMATION")
print("-"*100)
print("NAME    : ",a)
print("CLASS   : ",b)
print("SECTION : ",c)
print("-"*100)
print("                                           MARKS")
print("-"*100)
print("English       : ",d)
print("Economics     : ",e)
print("Accounts      : ",f)
print("BST           : ",g)
print("Informatics   : ",h)
print("-"*100)
print("Total Marks   : ",i)
print("Average Marks : ",j)
print("-"*100)
print("                                      GRADE AND STATUS")
print("-"*100)
if(j>90 and j<=100):
    print("Grade : A")
elif(j>80 and j<90):
    print("Grade : B")
elif(j>65 and j<80):
    print("Grade : C")
elif(j>50 and j<=65):
    print("Grade : D")
elif(j>=33 and j<=50):
    print("Grade : E")
elif(j<33):
    print("Grade : F")
print("-"*100)
if(j>=33):
    print("Final Status : Pass")
else:
    print("Final Status : Fail")
print("-"*100)
print("Remarks : ",r)
print("-"*100)